[package]
name = "lizard"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/surjolive/LIZARD"
description = "The native Rust implementation of the LIZARD programming language."

[dependencies]

[[bin]]
name = "lz"
path = "src/main.rs"

[[bin]]
name = "lizard"
path = "src/main.rs"
